stages:
  - Lint
  - Build
  - Deploy

variables:
  AMZ_REGISTRY: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/delegator-api
  GITLAB_REGISTRY: registry.gitlab.com/delegator-au
  IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

Flake8:
  stage: Lint
  allow_failure: true
  image: $GITLAB_REGISTRY/infrastructure/containers/python:latest
  only:
    - master
  script:
    - flake8 src/

Build:
  stage: Build
  image: $GITLAB_REGISTRY/infrastructure/containers/docker:latest
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  script:
    # docker-login to ecr
    - eval $(aws ecr get-login --no-include-email --registry-ids 650215746119)
    # docker-login to gitlab
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # build
    - docker pull $AMZ_REGISTRY:latest
    - docker build --build-arg COMMIT_SHA=$CI_COMMIT_SHORT_SHA -t $AMZ_REGISTRY:$IMAGE_TAG -t $AMZ_REGISTRY:latest -t $GITLAB_REGISTRY/dev/delegator-api --cache-from $AMZ_REGISTRY:latest src/
    # push tagged images
    - docker push $AMZ_REGISTRY:$IMAGE_TAG
    - docker push $AMZ_REGISTRY:latest
    - docker push $GITLAB_REGISTRY/dev/api

.deploy:
  stage: Deploy
  only:
    - master
  script:
    - "curl 
      -X POST
      -F token=4087c68b61838a88958e72580177a2 
      -F ref=master 
      -F variables[IMAGE]=$AMZ_REGISTRY:$IMAGE_TAG
      -F variables[DEPLOY_ENV]=$DEPLOY_ENV 
      -F variables[PROJECT]=delegator-api
      https://gitlab.com/api/v4/projects/14042887/trigger/pipeline"

Staging:
  extends: .deploy
  variables:
    DEPLOY_ENV: staging
  environment:
    name: $DEPLOY_ENV
    url: https://api.$DEPLOY_ENV.delegator.com.au/

Production:
  extends: .deploy
  when: manual
  variables:
    DEPLOY_ENV: production
  environment:
    name: $DEPLOY_ENV
    url: https://api.delegator.com.au/
