stages:
  - build
  - deployStaging

variables:
  AMZ_REGISTRY: 292374005836.dkr.ecr.ap-southeast-2.amazonaws.com
  AWS_DEFAULT_REGION: ap-southeast-2

build:
  stage: build
  image: docker:18.06
  before_script:
    - apk add python3 build-base
    - python3 -m ensurepip
    - pip3 install awscli
  tags:
    - docker
  script:
    # docker-login to ecr
    - eval $(aws ecr get-login --no-include-email)
    # create image registry repo if not exists
    - aws ecr create-repository --repository-name api || true
    # build, tag, and push commit
    - docker build -t $AMZ_REGISTRY/api:CI_COMMIT_SHORT_SHA .
    - docker push $AMZ_REGISTRY/api:CI_COMMIT_SHORT_SHA
    # tag and push latest
    - docker tag $AMZ_REGISTRY/api:CI_COMMIT_SHORT_SHA $AMZ_REGISTRY/api:latest
    - docker push $AMZ_REGISTRY/api:latest

deployStaging:
  stage: deployStaging
  image: python:3.7-alpine
  when: manual
  tags:
    - docker
  before_script:
    - pip install boto3
  script:
    - python deploy/deploy.py api staging
