version: '3.7'
services:
  # api:
  #   image: 008492826001.dkr.ecr.ap-southeast-2.amazonaws.com/api:latest
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     APP_ENV: Ci
  #   ports:
  #     - 5000:5000

  # reporting-cruncher:
  #   image: 008492826001.dkr.ecr.ap-southeast-2.amazonaws.com/reporting-cruncher:latest
  #   depends_on:
  #     - redis
  #   environment:
  #     APP_ENV: Ci
  #   ports:
  #     - 5005:5005

  # task_escalator:
  #   # image: 008492826001.dkr.ecr.ap-southeast-2.amazonaws.com/task-escalator:latest
  #   build:
  #     context: ../../task-escalator/src
  #   environment:
  #     DATABASE_URI: backburner:backburner@postgres/backburner
  #   depends_on:
  #     - postgres
  
  task_reminder:
    # image: 008492826001.dkr.ecr.ap-southeast-2.amazonaws.com/task-reminder:latest
    build:
      context: ../../task-reminder/src
    environment:
      DATABASE_URI: backburner:backburner@postgres/backburner
    depends_on:
      - postgres

  # pg_hero:
  #   image: ankane/pghero:latest
  #   environment:
  #     DATABASE_URL: postgres://backburner:backburner@postgres/backburner
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres

  postgres:
    # image: 008492826001.dkr.ecr.ap-southeast-2.amazonaws.com/postgres:latest
    build:
      context: ../../containers/postgres
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track='all'
    ports:
      - 5432:5432

  # redis:
  #   image: 008492826001.dkr.ecr.ap-southeast-2.amazonaws.com/reporting-cache:latest
  #   ports:
  #     - 6379:6379
