version: '3.7'
services:

  postgres:
    image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/postgres:latest
    # this command enable pg stat statements which pghero below uses
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track='all'
    ports:
      - 5432:5432

  redis:
    image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/redis:latest
    ports:
      - 6379:6379

  delegator-api:
    # use the image from ECR
    # image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/delegator-api:latest

    # build the api image instead
    image: delegator_api
    build:
      cache_from: 
        - delegator_api
      context: ../src/

    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
    - .env
    environment:
      APP_ENV: Docker
      # MOCK_SERVICES: 'true'
      # MOCK_AWS: 'true'
      AWS_DEFAULT_REGION: ap-southeast-2
    ports:
      - 5000:5000

  subscription-api:
    image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/subscription-api:latest
    restart: always
    environment:
      APP_ENV: Ci
    ports:
      - 5001:5001
    depends_on:
      - redis

  notification-api:
    image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/notification-api:latest
    restart: always
    env_file:
    - .env
    environment:
      APP_ENV: Docker
      AWS_DEFAULT_REGION: ap-southeast-2
    ports:
      - 5002:5002
    depends_on:
      - redis

  # OPTIONAL - if you run this then you will need to run the api
  # task_escalator:
  #   image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/task-escalator:latest
  #   environment:
  #     APP_ENV: Docker
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     AWS_DEFAULT_REGION: ap-southeast-2
  #   depends_on:
  #     - postgres
  
  
  # OPTIONAL - if you run this then you will need to run the api
  # task_reminder:
  #   image: 650215746119.dkr.ecr.ap-southeast-2.amazonaws.com/task-reminder:latest
  #   environment:
  #     APP_ENV: Docker
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     AWS_DEFAULT_REGION: ap-southeast-2
  #   depends_on:
  #     - postgres


  # OPTIONAL - gives postgres stats and info
  # pg_hero:
  #   image: ankane/pghero:latest
  #   environment:
  #     DATABASE_URL: postgres://delegator:delegator@postgres/delegator
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
