version: '3.7'
services:

  postgres:
    # image: 239304980652.dkr.ecr.ap-southeast-2.amazonaws.com/postgres:latest
    build:
      context: ../../containers/postgres
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track='all'
    ports:
      - 5432:5432

  redis:
    # image: 239304980652.dkr.ecr.ap-southeast-2.amazonaws.com/redis:latest
    build:
      context: ../../containers/redis
    ports:
      - 6379:6379

  delegator-api:
    image: delegator_api
    build:
      cache_from: 
        - delegator_api
      context: ../src/
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: Docker
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-southeast-2
    ports:
      - 5000:5000

  subscription-api:
    image: subscription_api
    build:
      cache_from: 
        - subscription_api
      context: ../../subscription-api/src/
    restart: always
    depends_on:
      - redis
    environment:
      APP_ENV: Ci
    ports:
      - 5001:5001

  notification-api:
    image: notification_api
    build:
      cache_from: 
        - notification_api
      context: ../../notification-api/src/
    restart: always
    environment:
      APP_ENV: Docker
    ports:
      - 5002:5002

  task_escalator:
    image: task_escalator
    build:
      cache_from: 
        - task_escalator
      context: ../../task-escalator/src
    environment:
      APP_ENV: Docker
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-southeast-2
    depends_on:
      - postgres
  
  task_reminder:
    image: task_escalator
    build:
      cache_from: 
        - task_escalator
      context: ../../task-reminder/src
    environment:
      APP_ENV: Docker
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-southeast-2
    depends_on:
      - postgres

  # pg_hero:
  #   image: ankane/pghero:latest
  #   environment:
  #     DATABASE_URL: postgres://delegator:delegator@postgres/delegator
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
