version: '3.7'
services:
  api:
    build:
      context: ../src
      dockerfile: Dockerfile
      args:
        FLASK_ENV: development
        APP_ENV: Docker
    command: pipenv run flask run --host 0.0.0.0 --reload
    ports:
      - 5000:5000
    volumes:
      - ../src:/app
  # nginx:
  #   build:
  #     context: nginx/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #     - 443:443
  postgres:
    build:
      context: ../../containers/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
