class Operations(str):
    ASSIGN = "ASSIGN"
    CANCEL = "CANCEL"
    CREATE = "CREATE"
    DELAY = "DELAY"
    DELETE = "DELETE"
    DISABLE = "DISABLE"
    DROP = "DROP"
    ENABLE = "ENABLE"
    GET = "GET"
    TRANSITION = "TRANSITION"
    UPDATE = "UPDATE"
    LOCK = "LOCK"
    UNLOCK = "UNLOCK"
