class TaskStatuses(str):
    SCHEDULED = "SCHEDULED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    CANCELLED = "CANCELLED"
    DELAYED = "DELAYED"
    COMPLETED = "COMPLETED"

    all = [SCHEDULED, READY, IN_PROGRESS, CANCELLED, DELAYED, COMPLETED]
